server:
  port: 8000

spring:
  application:
    name: zuul-service

zuul:
  routes:
    first-service:
      path: /first/**
      url: http://localhost:8081
    second-service:
      path: /second/**
      url: http://localhost:8082